// Generated by gencpp from file my_custom_msgs/CustomMessage.msg
// DO NOT EDIT!


#ifndef MY_CUSTOM_MSGS_MESSAGE_CUSTOMMESSAGE_H
#define MY_CUSTOM_MSGS_MESSAGE_CUSTOMMESSAGE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace my_custom_msgs
{
template <class ContainerAllocator>
struct CustomMessage_
{
  typedef CustomMessage_<ContainerAllocator> Type;

  CustomMessage_()
    : header()
    , rotation_matrix1()
    , rotation_matrix2()
    , translation_matrix1()
    , translation_matrix2()  {
      rotation_matrix1.assign(0.0);

      rotation_matrix2.assign(0.0);

      translation_matrix1.assign(0.0);

      translation_matrix2.assign(0.0);
  }
  CustomMessage_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , rotation_matrix1()
    , rotation_matrix2()
    , translation_matrix1()
    , translation_matrix2()  {
  (void)_alloc;
      rotation_matrix1.assign(0.0);

      rotation_matrix2.assign(0.0);

      translation_matrix1.assign(0.0);

      translation_matrix2.assign(0.0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef boost::array<double, 9>  _rotation_matrix1_type;
  _rotation_matrix1_type rotation_matrix1;

   typedef boost::array<double, 9>  _rotation_matrix2_type;
  _rotation_matrix2_type rotation_matrix2;

   typedef boost::array<double, 3>  _translation_matrix1_type;
  _translation_matrix1_type translation_matrix1;

   typedef boost::array<double, 3>  _translation_matrix2_type;
  _translation_matrix2_type translation_matrix2;





  typedef boost::shared_ptr< ::my_custom_msgs::CustomMessage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_custom_msgs::CustomMessage_<ContainerAllocator> const> ConstPtr;

}; // struct CustomMessage_

typedef ::my_custom_msgs::CustomMessage_<std::allocator<void> > CustomMessage;

typedef boost::shared_ptr< ::my_custom_msgs::CustomMessage > CustomMessagePtr;
typedef boost::shared_ptr< ::my_custom_msgs::CustomMessage const> CustomMessageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_custom_msgs::CustomMessage_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_custom_msgs::CustomMessage_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_custom_msgs::CustomMessage_<ContainerAllocator1> & lhs, const ::my_custom_msgs::CustomMessage_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.rotation_matrix1 == rhs.rotation_matrix1 &&
    lhs.rotation_matrix2 == rhs.rotation_matrix2 &&
    lhs.translation_matrix1 == rhs.translation_matrix1 &&
    lhs.translation_matrix2 == rhs.translation_matrix2;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_custom_msgs::CustomMessage_<ContainerAllocator1> & lhs, const ::my_custom_msgs::CustomMessage_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_custom_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_custom_msgs::CustomMessage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_custom_msgs::CustomMessage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_custom_msgs::CustomMessage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_custom_msgs::CustomMessage_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_custom_msgs::CustomMessage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_custom_msgs::CustomMessage_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_custom_msgs::CustomMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "25d16b0231a3ea0e2c99958078a36fe8";
  }

  static const char* value(const ::my_custom_msgs::CustomMessage_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x25d16b0231a3ea0eULL;
  static const uint64_t static_value2 = 0x2c99958078a36fe8ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_custom_msgs::CustomMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_custom_msgs/CustomMessage";
  }

  static const char* value(const ::my_custom_msgs::CustomMessage_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_custom_msgs::CustomMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# custom message for rotation and translation matrices with timestamp\n"
"Header header\n"
"float64[9] rotation_matrix1\n"
"float64[9] rotation_matrix2\n"
"float64[3] translation_matrix1\n"
"float64[3] translation_matrix2\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::my_custom_msgs::CustomMessage_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_custom_msgs::CustomMessage_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.rotation_matrix1);
      stream.next(m.rotation_matrix2);
      stream.next(m.translation_matrix1);
      stream.next(m.translation_matrix2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CustomMessage_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_custom_msgs::CustomMessage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_custom_msgs::CustomMessage_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "rotation_matrix1[]" << std::endl;
    for (size_t i = 0; i < v.rotation_matrix1.size(); ++i)
    {
      s << indent << "  rotation_matrix1[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.rotation_matrix1[i]);
    }
    s << indent << "rotation_matrix2[]" << std::endl;
    for (size_t i = 0; i < v.rotation_matrix2.size(); ++i)
    {
      s << indent << "  rotation_matrix2[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.rotation_matrix2[i]);
    }
    s << indent << "translation_matrix1[]" << std::endl;
    for (size_t i = 0; i < v.translation_matrix1.size(); ++i)
    {
      s << indent << "  translation_matrix1[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.translation_matrix1[i]);
    }
    s << indent << "translation_matrix2[]" << std::endl;
    for (size_t i = 0; i < v.translation_matrix2.size(); ++i)
    {
      s << indent << "  translation_matrix2[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.translation_matrix2[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_CUSTOM_MSGS_MESSAGE_CUSTOMMESSAGE_H
